version: "3.3"
services:
 db:
    container_name: 'database-postgres'
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=erp_processes_mng
      - POSTGRES_USER=erp_admin
      - POSTGRES_PASSWORD=erp_user_pass@pcr
 web:
    container_name: 'erp'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/erp
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=erp_processes_mng
      - POSTGRES_USER=erp_admin
      - POSTGRES_PASSWORD=erp_user_pass@pcr
    depends_on:
      - db