version: "3.3"
services:
  db:
    container_name: 'database-postgres'
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=erp_processes_mng
      - POSTGRES_USER=erp_admin
      - POSTGRES_PASSWORD=erp_user_pass@pcr
  backend:
    container_name: 'erp'
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    working_dir: /erp/src/backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/erp
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=erp_processes_mng
      - POSTGRES_USER=erp_admin
      - POSTGRES_PASSWORD=erp_user_pass@pcr
    depends_on:
      - db
  web:
    container_name: 'webapp'
    build: 
      context: .
      dockerfile: ./docker/webapp/Dockerfile
    working_dir: /erp/src/webapp/
    volumes:
      - .:/erp
    ports:
      - "4200:4200"
      - "49153:49153"
    command: ng serve --host 0.0.0.0 --poll 20
